language: python
python:
    - "2.7"
services:
    - redis-server
script:
    - python setup.py test
after_success:
  - coveralls
notifications:
  email:
    - alvarom@csail.mit.edu
    - cperivol@csail.mit.edu
    - sfelshin@csail.mit.edu

  on_success: always
  on_failure: always
