language: python
python:
    - "2.7.8"

script:
    - python setup.py test
after_success:
  - coveralls
notifications:
  email:
    - cperivol@csail.mit.edu

  on_success: always
  on_failure: always
