sudo: false
language: python
python:
    - "2.7"
services:
    - redis-server
install:
    - pip install coveralls
    - python setup.py install
script:
    - coverage run setup.py test
after_success:
    - coveralls
