sudo: false
language: python
python:
    - "2.7"
services:
    - postgresql
    - redis-server
install:
    - pip install coveralls
    - python setup.py install
before_script:
    - scripts/configure_db.py
script:
    - coverage run setup.py test
after_success:
    - coveralls
env:
    - WIKIPEDIABASE_FORCE_LIVE=true
